import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Layout from "@/components/Layout";
import { ConfigProvider, App } from "antd"; // ✅ Import App
import "@ant-design/v5-patch-for-react-19";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={false}>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <AntdRegistry>
                    <ConfigProvider theme={{ token: { colorBgLayout: "#f1f1f1" } }}>
                        <App> {/* ✅ Wrap children inside <App> */}
                            {children}
                        </App>
                    </ConfigProvider>
                </AntdRegistry>
            </body>
        </html>
    );
}
